# Sensors Topics
initial_cylinder_index: 0
sensor_current_threshold: 2
frequency: 30 #hz
stopper_sensor: 
  i2c_address: 0x40
  topic_name: stopper_count
pusher_sensor: 
  i2c_address: 0x41
  topic_name: pusher_count
# -------------------------
# Actuator Servers
## Note BOARD is the Pin Numbering System
stopper_server: 
  gpio: 17
  topic_name: stopper_action
pusher_server: 
  gpio: 22
  topic_name: pusher_action
# -------------------------
# Timers
timers: 
  t_sensor_stopper: 0.0         #1
  t_detection_reset : 0.0       #2
  t_stopper_reactivation: 5.0   #3
  t_sensor_pusher : 4.0         #4
  t_pusher_reset  : 3.0         #5
# -------------------------
# Camera Capture Topic
raw_image_topic_name: raw_image
# -------------------------
# Object Detection Action Server
detect_server:
  topic_name: object_detection
  model_path: "$(find jetson_detection)/models/best.engine"
  model_config: 0.7     # Filter Results
  number_of_frames_proc: 20