# Sensors Topics
initial_cylinder_index: 0
sensor_current_threshold: 2
frequency: 30 #hz
stopper_sensor: 
  i2c_address: 0x40
  topic_name: stopper_count
pusher_sensor: 
  i2c_address: 0x41
  topic_name: pusher_count
# -------------------------
# Actuator Servers
## Note BOARD is the Pin Numbering System
stopper_server: 
  gpio: 19
  topic_name: stopper_action
  delay_action: 2.0 #in seconds
pusher_server: 
  gpio: 21
  topic_name: pusher_action
  delay_action: 2.0 #in seconds
# -------------------------
# Pusher Queue Server
push_action_server:
  server_name: pusher_queue_server
# -------------------------
# Object Detection Action Server
detect_server:
  topic_name: object_detection
  model_path: "$(find jetson_detection)/models/best.engine"
  model_config: 0.7     # Filter Results