# Sensors Topics
initial_cylinder_index: 0
sensor_current_threshold: 2
frequency: 30 #hz
stopper_sensor: 
  i2c_address: 0x40
  topic_name: stopper_count
pusher_sensor: 
  i2c_address: 0x41
  topic_name: pusher_count
# -------------------------
# Actuator Servers
## Note BOARD is the Pin Numbering System
stopper_server: 
  gpio: 17
  topic_name: stopper_action
pusher_server: 
  gpio: 21
  topic_name: pusher_action
# -------------------------
# Timers
timers: 
  timer_1 : 5.0         
  timer_2 : 5.0      
  timer_3 : 5.0  
  timer_4 : 5.0        
  timer_5 : 5.0        
  timer_6 : 5.0      
# -------------------------
# Camera Capture Topic
raw_image_topic_name: raw_image
# -------------------------
# Object Detection Action Server
detect_server:
  topic_name: object_detection
  model_path: "$(find jetson_detection)/models/best.engine"
  model_config: 0.7     # Filter Results
  number_of_frames_proc: 20