# Sensors Topics
initial_cylinder_index: 0
sensor_current_threshold: 2
frequency: 30 #hz
stopper_sensor: 
  i2c_address: 0x40
  topic_name: stopper_count
pusher_sensor: 
  i2c_address: 0x41
  topic_name: pusher_count
# -------------------------
# Actuator Servers
## Note BCM is the Pin Numbering System
stopper_server: 
  gpio: 17
  topic_name: stopper_action
  delay_action: 2.0 #in seconds
pusher_server: 
  gpio: 22
  topic_name: pusher_action
  delay_action: 2.0 #in seconds
# -------------------------
# Pusher Queue Server
push_action_server:
  server_name: pusher_queue_server
# -------------------------
# Object Detection Action Server
detect_server:
  server_name: object_detection
  model_path: "$(find jetson_detection)/models/best.engine"
  frequency: 10
  model_config: 0.7     # Filter Results
  number_of_frames : 3  # The Detection result is the maximum detected class for number_of_frames
  ## Camera Capture Settings
  camera: {
    capture_width : 1280,
    capture_height : 720,
    fps : 59.9,
  }